spring:

  application:
    name: chatting-service #服务名称

eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://112.124.59.163:31011/eureka/ #配置注册中心地址