# Sa-Token 配置
sa-token:
  # -------------- SSO-模式一相关配置  (非模式一不需要配置)
  # cookie:
  # 配置Cookie作用域
  # domain: stp.com

  # ------- SSO-模式二相关配置
  sso:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    allow-url: "*"
    # 是否打开单点注销功能
    is-slo: true

    # ------- SSO-模式三相关配置 （下面的配置在SSO模式三并且 is-slo=true 时打开） -------
    # 是否打开模式三
    #    isHttp: true
    # 接口调用秘钥（用于SSO模式三的单点注销功能）
    #    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）


spring:

  application:
    name: user-service #服务名称

  rabbitmq:
    host: 81.68.233.64
    port: 5672
    username: ENC(t4zbGzLsn3Tb+gGqofPZ1w==)
    password: ENC(uvFPbhcKZRa1IfScG7qz3iUMvjjwHF2M)


eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      #112.124.59.163:31011
      defaultZone: http://112.124.59.163:31011/eureka/ #配置注册中心地址

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}



