spring:
  datasource:
    username: uniplus_good_information_service
    password: soa_uniplus_good_information
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.68.233.64:3306/uniplus_good_information
server:
  port: 8085